version: '3'

services:
  redis_server:
      image: "redis"
      ports:
          - "6379:6379"
      restart: always

  benny:
      build: .
      environment:
          - AWS_ACCESS_KEY_ID=$AWSAccessKeyId
          - AWS_SECRET_ACCESS_KEY=$AWSSecretKey
      ports:
          - "5000:5000"
      depends_on:
        - redis_server

