app:
    build: .
    environment:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
    ports:
        - "5000:5000"
    links:
        - redis

redis:
    image: "redis"
    ports:
        - "6379:6379"
    restart: always